site_name: mkdocs_puml
repo_url: https://github.com/MikhailKravets/mkdocs_puml
repo_name: mkdocs_puml
theme:
  name: material
  logo: assets/logos/icon-white.svg
  favicon: assets/logos/icon-square.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - content.tooltips
    - toc.follow
plugins:
  - search
  - awesome-pages
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml
      puml_keyword: plantuml
      theme:
        url: https://raw.githubusercontent.com/MikhailKravets/mkdocs_puml/themes/themes/
        light: material/teal-light
        dark: material/deep-orange-dark
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
